---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rex-ui
  labels:
    app.kubernetes.io/name: rex
    app.kubernetes.io/instance: rex-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rex
      app.kubernetes.io/instance: rex-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rex
        app.kubernetes.io/instance: rex-ui
    spec:
      containers:
        - name: ui
          image: sierrasoftworks/rex-ui:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 150Mi
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              port: http
              path: /
            initialDelaySeconds: 5
            periodSeconds: 1
          livenessProbe:
            httpGet:
              port: http
              path: /
            initialDelaySeconds: 30
            periodSeconds: 1
