---
apiVersion: v1
kind: Service
metadata:
  name: rex-ui
spec:
  selector:
    app.kubernetes.io/name: rex
    app.kubernetes.io/instance: rex-ui
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP